### ISSUE TITLE
Doesn't even work with provided examples

### ISSUE THREAD

**Issue by gitgitwhat** [spdx/tools-python#255]
This tool, and even the online version, fail with the provided SPDX samples found here(https://github.com/spdx/tools-python/tree/main/data).  

Trying to verify the RDX example using this command `java -jar tools-java-1.1.2-SNAPSHOT-jar-with-dependencies.jar Verify spdx.rdf` causes this error:

```
23:10:21.232 [main] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 159 column 128): Invalid byte 1 of 1-byte UTF-8 sequence.
Exception in thread "main" org.apache.jena.shared.JenaException: org.xml.sax.SAXParseException; lineNumber: 159; columnNumber: 128; Invalid byte 1 of 1-byte UTF-8 sequence.
        at org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler.fatalError(RDFDefaultErrorHandler.java:62)
        at org.apache.jena.rdfxml.xmlinput.impl.ARPSaxErrorHandler.fatalError(ARPSaxErrorHandler.java:47)
        at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.warning(XMLHandler.java:199)
        at org.apache.jena.rdfxml.xmlinput.impl.XMLHandler.fatalError(XMLHandler.java:229)
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:181)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:306)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:3085)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at org.apache.jena.rdfxml.xmlinput.impl.RDFXMLParser.parse(RDFXMLParser.java:95)
        at org.apache.jena.rdfxml.xmlinput.JenaReader.read(JenaReader.java:163)
        at org.apache.jena.rdfxml.xmlinput.JenaReader.read(JenaReader.java:152)
        at org.apache.jena.rdfxml.xmlinput.JenaReader.read(JenaReader.java:221)
        at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:253)
        at org.spdx.spdxRdfStore.RdfStore.deSerialize(RdfStore.java:523)
        at org.spdx.tools.Verify.verify(Verify.java:128)
        at org.spdx.tools.Verify.main(Verify.java:80)
        at org.spdx.tools.Main.main(Main.java:52)
Caused by: org.xml.sax.SAXParseException; lineNumber: 159; columnNumber: 128; Invalid byte 1 of 1-byte UTF-8 sequence.
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
        at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
        ... 20 more
Caused by: com.sun.org.apache.xerces.internal.impl.io.MalformedByteSequenceException: Invalid byte 1 of 1-byte UTF-8 sequence.
        at java.xml/com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.invalidByte(UTF8Reader.java:702)
        at java.xml/com.sun.org.apache.xerces.internal.impl.io.UTF8Reader.read(UTF8Reader.java:568)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1699)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.scanContent(XMLEntityScanner.java:1052)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanContent(XMLDocumentFragmentScannerImpl.java:1555)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2846)
        ... 17 more

```

Meanwhile trying to verify the same RDX file online throws this error:

`Cannot invoke "String.equals(Object)" because the return value of "org.apache.jena.rdf.model.Resource.getURI()" is null`

Trying the other example files throw other errors.  The fact that both the CLI tool and the online verifier fail indicate that either the examples are incorrect or something is really busted with the tools.

**Comment by gitgitwhat** [comment]
Talk about fast service!  Thanks for the quick response.

Encoding issue seems odd but when I `wget`'d the RDX sample to my Linux box (vs copying it over from my Windows system) and ran the verify command I now get this error.  Maybe it's related to your PR in that the SPDXRef aren't valid?  If that's the case, curious why these samples were posted in the first place?  More critically, why the tools don't handle error conditions better.  That's how serious vulns are formed.

```
Exception in thread "main" java.lang.NullPointerException
        at org.spdx.spdxRdfStore.CompatibilityUpgrader.lambda$0(CompatibilityUpgrader.java:135)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at org.apache.jena.util.iterator.ExtendedIterator.forEach(ExtendedIterator.java:82)
        at org.spdx.spdxRdfStore.CompatibilityUpgrader.upgradeHasFiles(CompatibilityUpgrader.java:131)
        at org.spdx.spdxRdfStore.CompatibilityUpgrader.upgrade(CompatibilityUpgrader.java:106)
        at org.spdx.spdxRdfStore.RdfStore.deSerialize(RdfStore.java:526)
        at org.spdx.tools.Verify.verify(Verify.java:128)
        at org.spdx.tools.Verify.main(Verify.java:80)
        at org.spdx.tools.Main.main(Main.java:52)
```

**Comment by meretp** [comment]
I have opened a new issue (#256) concerning the example files in python-tools and would suggest to close this one as it also contains java-specific issues (even if they are already fixed). Are you okay with that?
