### ISSUE TITLE
Assigning SpdxNoAssertion to license_concluded results in type error

### ISSUE THREAD

**Issue by goneall** [spdx/tools-python#823]
Programmatically setting `SpdxNoAssertion` to a package `concluded_license` property results in an error.

Let me know if there is a different approach to assigning a NoAssertion value.

See below for the details:

```
>>> from spdx_tools.spdx.model.package import Package
>>> from spdx_tools.spdx.model import SpdxNoAssertion
>>> pkg = Package(spdx_id='SpdxRef-xx', name='name', download_location='https://example.com', files_analyzed=False)
>>> pkg.license_concluded=SpdxNoAssertion
Traceback (most recent call last):
  File "C:\Users\gary\git\scaffold\venv\Lib\site-packages\spdx_tools\common\typing\dataclass_with_properties.py", line 32, in set_field_with_error_conversion
    set_field(self, value)
  File "<@beartype(spdx_tools.common.typing.dataclass_with_properties.make_setter.set_field) at 0x170562ee200>", line 32, in set_field
beartype.roar.BeartypeCallHintParamViolation: Method spdx_tools.common.typing.dataclass_with_properties.make_setter.set_field() parameter value=<class 'spdx_tools.spdx.model.spdx_no_assertion.SpdxNoAssertion'> violates type hint typing.Union[boolean.boolean.Expression, spdx_tools.spdx.model.spdx_no_assertion.SpdxNoAssertion, spdx_tools.spdx.model.spdx_none.SpdxNone, NoneType], as type <class 'spdx_tools.spdx.model.spdx_no_assertion.SpdxNoAssertion'> not <class "boolean.boolean.Expression">, <class "spdx_tools.spdx.model.spdx_no_assertion.SpdxNoAssertion">, <class "spdx_tools.spdx.model.spdx_none.SpdxNone">, or <class "builtins.NoneType">.
```

**Comment by armintaenzertng** [comment]
Hi Gary, `SpdxNoAssertion` is the name of the class. Try instantiating it, i.e. `pkg.license_concluded=SpdxNoAssertion()`.

**Comment by goneall** [comment]
Thanks @armintaenzertng - I thought it might be related to my (not so great) Python skills ;)

This resolved the issue
